- name: Calculate the list of snapshots
  block:
  - name: Get list of volumes
    ansible.builtin.command: "lvs --select 'lv_name =~ {{ remove_snapshot_set_name }}$ && origin != \"\"' --reportformat json "
    register: remove_snapshot_lvs_response
    changed_when: false
  - name: Get LV dict List
    ansible.builtin.set_fact:
      remove_snapshot_snapshots: "{{ (remove_snapshot_lvs_response.stdout | from_json).report[0].lv }}"

- name: Remove snapshots
  community.general.lvol:
    state: absent
    vg: "{{ item.vg_name }}"
    lv: "{{ item.origin }}"
    snapshot: "{{ item.lv_name }}"
    force: true
  loop: "{{ remove_snapshot_snapshots }}"

- name: Remove boot backup
  ansible.builtin.file:
    path: "/root/boot-backup-{{ remove_snapshot_set_name }}.tgz"
    state: absent
