---
- name: Assert shrink_lv_devices
  ansible.builtin.assert:
    that:
    - shrink_lv_devices is defined
    - shrink_lv_devices | type_debug == "list"
    - shrink_lv_devices | length > 0
    fail_msg: shrink_lv_devices must be a list and include at least one element

- name: Assert current kernel version is the default
  ansible.builtin.include_tasks: check_kernel.yaml

- name: Check all devices
  ansible.builtin.include_tasks: check_device.yaml
  loop: "{{ shrink_lv_devices }}"
